baseURL: https://drphilbe.com
languageCode: be-nl
title: Dr Philippe Brewaeys - Plastic surgeon

module:
  imports:
    path: github.com/olbrew/hugo-hero-theme

params:
  google_analytics_id: ""

  logo:
    mobile: logo.png
    mobile_height: 36px
    mobile_width: 66px
    desktop: logo.png
    desktop_height: 30px
    desktop_width: 250px
    alt: Dr Philippe Brewaeys - Plastic surgeon logo

  homepage_meta_tags:
    meta_description: Dr Philippe Brewaeys is a plastic surgeon in Antwerp, Belgium.
    meta_og_title: Dr Philbe
    meta_og_type: website
    meta_og_url: https://www.drphilbe.com
    meta_og_image: https://www.drphilbe.com/img/hero.jpg
    meta_og_description: Dr Philippe Brewaeys is a plastic surgeon in Antwerp, Belgium.
    meta_twitter_card: summary
    meta_twitter_creator: '@olbrew'

menu:
  main:
    - name: Contact
      url: '#contact'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Book appointment
      url: '#book'
      weight: 3
permalinks:
  post: /:year/:month/:day/:slug/
  pages: /:filename/
